
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import bcrypt from 'bcryptjs'

export async function POST(request: NextRequest) {
    try {
        const body = await request.json()
        const { profile, answers, messages } = body

        if (!profile?.email || !profile?.name) {
            return NextResponse.json(
                { error: 'Nome e Email são obrigatórios.' },
                { status: 400 }
            )
        }

        // 1. Find or Create User
        let client = await prisma.client.findUnique({
            where: { email: profile.email }
        })

        if (!client) {
            // Create a temporary password for the user to access the portal later
            // In a real flow, we might email this or use a magic link
            // For now, setting a default that the user would reset or receive via email
            const tempPassword = Math.random().toString(36).slice(-8)
            const hashedPassword = await bcrypt.hash(tempPassword, 10)

            client = await prisma.client.create({
                data: {
                    name: profile.name,
                    email: profile.email,
                    phone: profile.phone,
                    password: hashedPassword,
                    country: 'Brasil', // Default based on context
                    nationality: profile.nationality,
                    age: parseInt(profile.age) || null,
                    education: profile.education,
                    targetCountry: profile.country, // Destination from profile
                    visaType: profile.visaType,
                    source: 'AI_CONSULTATION_LANDING',
                    status: 'LEAD'
                }
            })

            // Enviar email de boas-vindas com senha
            try {
                const baseUrl = process.env.NEXTAUTH_URL || 'http://localhost:3000'
                await fetch(`${baseUrl}/api/notifications/email`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        to: client.email,
                        template: 'welcome_lead',
                        clientId: client.id,
                        variables: {
                            client_email: client.email,
                            temp_password: tempPassword,
                            login_url: `${baseUrl}/cliente/login`
                        }
                    })
                })
                console.log(`📧 Email de boas-vindas enviado para ${client.email}`)
            } catch (emailError) {
                console.error('❌ Falha ao enviar email de boas-vindas:', emailError)
            }
        } else {
            // Update existing lead with new profiling data
            client = await prisma.client.update({
                where: { id: client.id },
                data: {
                    name: profile.name, // Update name if provided
                    phone: profile.phone || client.phone,
                    targetCountry: profile.country || client.targetCountry,
                    visaType: profile.visaType || client.visaType,
                    education: profile.education || client.education,
                    updatedAt: new Date()
                }
            })
        }

        // 2. Create the Consultation Record (Locked)
        // We store the "Draft" result in the result field but keep status SCHEDULED/PENDING
        // The dashboard will only show the full result if status is COMPLETED or a payment is linked
        const consultation = await prisma.consultation.create({
            data: {
                clientId: client.id,
                type: 'AI_ANALYSIS',
                status: 'SCHEDULED', // Indicates waiting for payment/action
                score: Math.min(profile.score || 50, 100), // Default score from frontend logic
                result: {
                    raw_profile: profile,
                    messages: messages,
                    generated_analysis: body.analysisResult // The full JSON analysis generated by frontend
                },
                recommendation: body.analysisResult?.recommendation || 'Aguardando desbloqueio',
                timeline: body.analysisResult?.timeline,
                notes: 'Pré-análise gerada via Chat IA. Aguardando pagamento para desbloqueio completo.'
            }
        })

        return NextResponse.json({
            success: true,
            clientId: client.id,
            consultationId: consultation.id,
            redirectUrl: `/checkout-moderno?product=pre-analise&clientId=${client.id}&consultationId=${consultation.id}`
        })

    } catch (error) {
        console.error('❌ Erro no onboarding IA:', error)
        return NextResponse.json(
            { error: 'Erro ao processar dados.' },
            { status: 500 }
        )
    }
}
