version: '3.8'

services:
  visa2any:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    
  # Development service for hot reload
  visa2any-dev:
    build:
      context: .
      target: deps
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped